### PR TITLE
style(ibl): update highlights for indent-blanklines

### PR DESCRIPTION
**Pull request by rgruyters**
Use new (shortend) syntax for indent-blankline. (ibl)

### CODE REVIEW

**Comment by rgruyters** [comment]
Do we want to set coloring for `IblWhitespace`?

**Comment by mvllow** [comment]
I think we should keep the old highlights around for backwards compatibility. As far as IblWhitespace, what it is set to by default? We may need to also set IblWhitespace under our transparency highlights to remove the background as well.

**Comment by rgruyters** [comment]
I have updated the PR and revert the old highlights, added the `IblWhitespace` and added ibl highlights to the transparency section.

**Comment by mvllow** [comment]
Thank you for the updated highlights :)

**Pull request merged**
