### PR TITLE
feat: Add nvim-notify highlights

### PR DESCRIPTION
**Pull request by danymat**
My take on vim-notify highlights 💪🏻 🤩 

Capture d’écran 2022-02-08 à 19 41 45

New highlights:

image

### CODE REVIEW

**Comment by mvllow** [comment]
thank you 😌

**Comment by will** [comment]
Thank you for this, I've been using it for a while. On the light mode the default info is hard to read though. I was going to submit a PR, but I'm not sure the best way to make the green darker for just that mode. 

```lua
vim.notify("error", vim.lsp.log_levels.ERROR)
vim.notify("warn", vim.lsp.log_levels.WARN)
vim.notify("info", vim.lsp.log_levels.INFO)
vim.notify("debug", vim.lsp.log_levels.DEBUG)
vim.notify("trace", vim.lsp.log_levels.TRACE)
```

image

If it's a super easy thing to do and either of you are quick at it I'd really appreciate it. If it's more work and you'd rather not do it, I'm also happy to submit a PR if you give me some guidance.

**Comment by will** [comment]
Wait actually did this commit get lost in the refactor? 

```
~/.l/s/n/s/p/p/s/rose-pine (main)> git lg
* 3de9dad - (grafted, HEAD -> main, origin/main, origin/HEAD) fix-named-blend-styles (3 weeks ago) <mvllow>
* b425bbd - (grafted, tag: v1.0.0) breaking-move-to-lua-config-64 (3 weeks ago) <not>
* b64956b - (grafted, tag: v1.0.0-canary.0) fix-galaxyline-palette (4 weeks ago) <mvllow>
* 41661f1 - (grafted, tag: v0.5.1) feat-Add-nvim-notify-highlights-66 (4 weeks ago) <Daniel Mathiot>
* 5cd9fe3 - (grafted, tag: 0.5.0) update-active-match-highlight (4 weeks ago) <mvllow>
* 3e56a0b - (grafted, tag: v0.4.0) Update-readme.md (6 weeks ago) <not>
* 25e7f54 - (grafted, tag: v0.3.0) feat-Add-lsp_signature-highlight-54 (9 weeks ago) <Daniel Mathiot>
* d16fc73 - (grafted, tag: v0.2.0) feat-add-TSStringSpecial (10 weeks ago) <mvllow>
* 4b63d8d - (grafted, tag: v0.1.0) feat-add-vim.g.rose_pine_inactive_background (3 months ago) <mvllow>
* da185c1 - (grafted, tag: v0.0.1) remove-thanks-to-section (7 months ago) <not>
~/.l/s/n/s/p/p/s/rose-pine (main)> rg Notify
~/.l/s/n/s/p/p/s/rose-pine (main) [1]>
```

The word `Notify` is maybe not in the repo at all anymore?

**Comment by mvllow** [comment]
Hmm I'll have to double check, thanks for pointing this out 😌

**Comment by will** [comment]
I sent a fix to re-add these #72

**Pull request merged**
