### PR TITLE
typo and grammar fixed, Bonus: clarifying the option effect

### PR DESCRIPTION
**Pull request by HectorOvid**
Trying to make the description in the readme regarding options for highlighting better.

### CODE REVIEW

**Comment by HectorOvid** [comment]
k

**Comment by mvllow** [comment]
Oh, I actually don't think that documentation was meant to be there—we ended up going a different direction (see https://github.com/rose-pine/neovim/blob/4ac66839a5cd138f26a2a107b9dd233177260346/lua/rose-pine/theme.lua#L605).

Feel free to document that new option if you'd like ([related PR](https://github.com/rose-pine/neovim/pull/171)) :)

We can remove the other option from the readme.

**Comment by HectorOvid** [comment]
Ya, the option is not used any more :D in code
i removed the mention in readme

Is Search a good example for the inherit usage? Not quite sure since i'm pretty new to nvim and its plugins

**Comment by mvllow** [comment]
Search could be good, anything that setting inherit to false would be useful for :)

**Comment by HectorOvid** [comment]
not sure if you saw, I added an example with Search in a commit above.

U think this is expressive enough? :)

**Comment by mvllow** [comment]
Perfect, thanks for the contribution!

**Pull request merged**
