### PR TITLE
fix: Make extent/size of floating windows clearer

### PR DESCRIPTION
**Pull request by briandipalma**
I hesitate to call this a fix but after this change LSP floating windows look like this...

I can't paste screenshots in this textarea... let me raise the PR and see if I can paste them in the comments.

### CODE REVIEW

**Comment by briandipalma** [comment]
image

**Comment by briandipalma** [comment]
This is what they look like without the change:

image

**Comment by briandipalma** [comment]
This is with the border set to:

```lua
local border = {
      {"🭽", "FloatBorder"},
      {"▔", "FloatBorder"},
      {"🭾", "FloatBorder"},
      {"▕", "FloatBorder"},
      {"🭿", "FloatBorder"},
      {"▁", "FloatBorder"},
      {"🭼", "FloatBorder"},
      {"▏", "FloatBorder"},
}
```

Which is a lot of padding top and bottom IMO but looks better than the builtin versions as they put the border character in the middle of the terminal character. I might raise an issue in Neovim about that and try and reduce the top/bottom padding of the default ones to be more like the border I have defined above.

**Comment by briandipalma** [comment]
Ah, wait I can't reduce the padding it's one character...oh well I still think the characters should be at the border not in the middle so I might raise an issue about that.

**Comment by mvllow** [comment]
I agree that _with_ your custom borders having the background extended is nicer looking. I'm curious if we set `FloatBorder` background and the user is not using borders, does anything change? If not then I don't mind adding this in. Perhaps we can document your border characters in the readme somewhere.

Currently I think borders are disabled by default for the floats you mentioned but enabled for some plugins such as telescope.nvim. Not sure if those border characters are shared.

**Comment by briandipalma** [comment]
Oh yeah, I'll get some screenshots tomorrow without borders.

**Comment by briandipalma** [comment]
This is what it looks like with my change:

border: "none"
image

border: "single"
image

border: "double"
image

border: "rounded"
image

border: "solid"
image

border: "shadow"
image

Custom border - the way I think Neovim should be by default for the single/double/rounded borders above
image

telescope
image

I'll post screenshots without my change next.

**Pull request closed without merging**
