### PR TITLE
feat: color for flash

### PR DESCRIPTION
**Pull request by Asthestarsfalll**
- #173 

before:

after:

### CODE REVIEW

**Comment by mvllow** [comment]
Thank you for adding this; because `Substitute` is not specific to a single plugin and is available in other situations, e.g. `:%s/abc/xyz/`, we should move this up into the base highlights.

As far as the colour, what you have is fine and feel free to leave it but I'm curious how you feel about something blended, e.g. `Substitute = { fg = p.love, bg = p.love, blend = 10 }`.

**Comment by Asthestarsfalll** [comment]
I have tested this before:


The contrast appears to be minimal as the `blend` effect causes the background to appear dimmer.

So I think the better choice is to use different colour of bg and fg without `blend`

**Comment by mvllow** [comment]
That makes sense. So let's move this to ~ line 76, below `['SpellRare'] = { sp = p.subtle, undercurl = true },` because it's not specific to "folke/flash.nvim". And for that same reason, it's probably best to also set the `fg = p.base` because when you do `:%s/abc/xyz/` it becomes hard to read on some matches. If you have any questions let me know, I'm happy to make these adjustments myself too if needed :)

**Comment by mvllow** [comment]
Grazie!

**Pull request merged**
