### PR TITLE
chore: update highlights for which-key.nvim

### LINKED ISSUE #285: bug: which-key title is not affected by extend_background_behind_borders
### Neovim version (nvim -v)

v0.10.0

### Terminal / multiplexer

Kitty / tmux

### Describe the bug

The title in the center of a which-key popup isn't affected by the `extend_background_behind_borders = true` option leading it to look janky and out of place if this option is set, when everything else (eg. Telescope, etc appears as it should). 

Screenshot of behaviour happening for which-key: 

Screenshot to show what it should look like (eg. Telescope):

### Repro

_No response_

### PR DESCRIPTION
**Pull request by sjclayton**
Updates highlight groups that have changed / been added for [which-key.nvim](https://github.com/folke/which-key.nvim), which has just had a new major version release (v3).

Fixes #285

### CODE REVIEW

**Comment by sjclayton** [comment]
This is ready to go as-is... 

I will submit another PR addressing the improving the display of the icon highlight groups, the way in which they are handled in which-key is kind of a bit odd.

**Comment by sjclayton** [comment]
I just noticed I was on nightly when I was working on this, and when I switched back to nvim v0.10.0 the fixes don't work... So will have to put this on hold for now.

**Comment by sjclayton** [comment]
After some investigation I have determined that there is a bug in which-key which is causing the fix not to take affect on the stable version of Neovim.

So as far as things being correct here, it would appear that everything is good now for this to be merged as-is. 😀

**Comment by mvllow** [comment]
Thank you for the thorough PR, much appreciated :)

**Pull request merged**
