### PR TITLE
Remove background for popups

### PR DESCRIPTION
**Pull request by danymat**
This commit removes the subtle surface that was not appealing for the eyes:

Before:

Capture d’écran 2021-12-01 à 10 24 20

After:

Capture d’écran 2021-12-01 à 10 23 48

Capture d’écran 2021-12-01 à 10 45 14

Motivated by this: https://www.reddit.com/r/neovim/comments/r5kwg7/rounded_corners_for_popup_menus/

### CODE REVIEW

**Comment by danymat** [comment]
Hello, sorry for the ping, did you have time to take a look ?

**Comment by mvllow** [comment]
Ope so sorry, I added some comments yesterday but didn’t realise you have to “finish review” for them to show 🤭

**Comment by mvllow** [comment]
Thank you!

**Comment by danymat** [comment]
Hello @mvllow, I just saw that you reverted this PR, do you have any reason why ?

**Comment by mvllow** [comment]
Sorry for the confusion! Glad you found the option to enable that again 😌

**Pull request merged**
