### PR TITLE
Support for Neorg

### PR DESCRIPTION
**Pull request by danymat**
Hello,

I'm one of the core contributors of Neorg, and I daily use rose-pine (I even try to promote it to the masses lol)

I'm adding custom rose-pine support for Neorg format, and will mark this PR to ready for review when I think it's time to be merged.

PS: The new contrib section was really reeeaaaly useful for me

### CODE REVIEW

**Comment by danymat** [comment]
At the moment, I have something like this:

Capture d’écran 2021-11-09 à 11 51 01

**Comment by mvllow** [comment]
Thank you for the kind words and for sharing Rosé Pine with others! Looking forward to this lovely addition 🥰

**Comment by danymat** [comment]
I'm pausing for a few days the PR development, because we are modifying the parser for the upcoming days. I will continue providing hl for Neorg when everything is merged

**Comment by danymat** [comment]
Hello ! We updated Neorg Parser and it seems to continue to work well with these highlights. I submitted the review for the merge.

**Comment by mvllow** [comment]
Would you mind rebasing? Also, it may be a good idea to use `config.colors.headings.h1` etc. for the headings/prefix, similar to what we do for markdown so the user can override easily.

**Full example**

```lua
markdownH1 = { fg = config.colors.headings.h1, style = 'bold' },
markdownH1Delimiter = { fg = config.colors.headings.h1 },
```

I used your colours as the defaults for `config.colors.headings` so it should look the same.

Excited for this one 😌

**Comment by danymat** [comment]
Tell me if it's good for you !

**Pull request merged**
