### PR TITLE
Add pounce highlights

### PR DESCRIPTION
**Pull request by danymat**
Hello, when discovering this amazing plugin, I wanted to add Rose pine hl to it.

This is my take:

image

Original:

Capture d’écran 2022-01-25 à 00 13 59

### CODE REVIEW

**Comment by mvllow** [comment]
maybe a slightly transparent background color would be easier to read? or does it look okay to you – screenshot may make it a little harder than it actually is

**Comment by ikws4** [comment]
This is my attempt, what do you think @mvllow @danymat 
Screen Shot 2022-01-25 at 8 56 06 AM

**Comment by mvllow** [comment]
that does seem a little easier to read. because i don't use that plugin (therefore don't understand the desired look) whatever y'all can agree on i'll merge 😌

**Comment by danymat** [comment]
> This is my attempt, what do you think @mvllow @danymat 
> 
> Screen Shot 2022-01-25 at 8 56 06 AM
> 
> 

Can you show us the `PounceMatch` and `PounceGap`?

**Comment by ikws4** [comment]
> > This is my attempt, what do you think @mvllow @danymat
> > Screen Shot 2022-01-25 at 8 56 06 AM
> 
> Can you show us the `PounceMatch` and `PounceGap`?

> 

I just link them to `hl-Search`, which is define at here https://github.com/rose-pine/neovim/blob/9344ec79352eae505b9b65a9054457e013860f11/lua/rose-pine/theme.lua#L71

**Comment by danymat** [comment]
Nice, @ikws4, you can port your PR then, I'm closing mine

**Pull request closed without merging**
